version: "3"

services:
  bot:
    build:
        context: .
        dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONIOENCODING=utf-8
    restart: always
